### ISSUE TITLE
ModuleNotFoundError: No module named 'neuralnet.dataset'

### ISSUE THREAD

**Issue by MMVpA** [LearnedVector/A-Hackers-AI-Voice-Assistant#45]
Hello,
when I run the engine.py from the Wakeword folder I got this Error.
I have installed neuralnet, but I still got this Error. Have I done something wrong?
I think you can't do so much wrong by install a Module with pip.
If you need more Information please write. I don't know what would help.

Niklas

**Comment by Til-de** [comment]
Hello, 
Did you found a solution for this problem?

Til

**Comment by CracKCatZ** [comment]
@Til-de you try to import a file from neuralnet in this case I think it is dataset make sure that dataset is a file which exists and ist located in this folder. If not I would probably try to install the repo again with the - - recursive assignment.

Ps: I hope I could help you out with this because I've never ran in such an error before;)

**Comment by Til-de** [comment]
I found the problem. 
I installed the package neuralnet, but it means the folder neuralnet.
Thank you for the answer!
Til
